name: concordia
channels:
- conda-forge
dependencies:
- attrs
- pandas >=1.1
- pyyaml
- xlrd >=2.0
- openpyxl
- matplotlib
- seaborn
- pyomo
- pytest
- geopandas
- netcdf4
- h5netcdf
- dask
- xarray
- cf_xarray
- flox
- filelock
- geoutils
- bottleneck
- deprecated
- pycountry
- dominate
- python-slugify
- seaborn
- tqdm
- jupytext
- ipykernel
- pip
- pip:
  - pandas-indexing[units] >=0.2.10
  - ptolemy-iamc
  # Need to integrate new indexraster changes into ptolemy
  - git+https://github.com/iiasa/ptolemy.git@add-index-raster#egg=aneris-iamc
  - git+https://github.com/iiasa/aneris.git@workflow#egg=aneris-iamc
  - -e .
