name: concordia
channels:
- conda-forge
dependencies:
- pandas >=1.1
- pyyaml
- xlrd >=2.0
- openpyxl
- matplotlib
- seaborn
- pyomo
- pytest
- geopandas
- netcdf4
- h5netcdf
- rioxarray
- deprecated

- ipykernel
- pip
- pip:
  - ptolemy-iamc
  - git+https://github.com/iiasa/aneris.git@workflow#egg=aneris-iamc
  - -e . 