name: concordia
channels:
- conda-forge
dependencies:
- pandas >=1.1
- pyyaml
- xlrd >=2.0
- openpyxl
- matplotlib
- seaborn
- pyomo
- pytest
- geopandas
- netcdf4
- h5netcdf
- dask
- xarray
- flox
- bottleneck
- deprecated
- pycountry
- dominate
- python-slugify
- seaborn
- tqdm
- jupytext

- ipykernel
- pip
- pip:
  - pandas-indexing[units]
  - ptolemy-iamc
  - git+https://github.com/iiasa/aneris.git@workflow#egg=aneris-iamc
  - -e . 