out_path: "../results"
data_path: "../data/<my project>" # this needs to be changed based on where you want to store your own data
variabledefs_path: "../data/variabledefs-<my project>.csv"

history_path: "$data_path/historical"
scenario_path: "$data_path/scenarios"
gridding_path: "$data_path/gridding_process_files"
proxy_path: "$data_path/gridding_process_files/proxy_rasters"
postprocess_path: "$data_path/postprocessing"

encoding:
  zlib: true
  complevel: 2

regionmappings:
  MyModelName:
    path: "$scenario_path/regionmapping_mymodelname.csv"
    country_column: "CountryCode"
    region_column: "RegionCode"
    sep: ";"

country_combinations:
  sdn_ssd: ["ssd", "sdn"]
  isr_pse: ["isr", "pse"]
  srb_ksv: ["srb", "srb (kosovo)"]

variable_template: "CEDS+|9+ Sectors|Emissions|{gas}|{sector}"
base_year: 2020

luc_sectors:
  - "Agricultural Waste Burning"
  - "Grassland Burning"
  - "Forest Burning"
  - "Peat Burning"
  - "Agriculture"
  - "Aggregate - Agriculture and LUC"
  - "CDR Afforestation"

ftp:
  server: "127.0.0.1"
  port: 21
  user: anonymous
  password: ""
